# Generated by Django 3.1.4 on 2020-12-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
