# Generated by Django 3.1.4 on 2020-12-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victoria', '0002_reserva_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
