# Generated by Django 3.1.4 on 2020-12-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victoria', '0003_auto_20201222_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='status',
        ),
        migrations.AddField(
            model_name='reserva',
            name='up_to_date',
            field=models.BooleanField(default=True, verbose_name='Próximas fechas'),
        ),
    ]
